services:
  - type: web
    name: hackyeah2026
    runtime: docker
    region: frankfurt
    plan: free
    branch: main
    autoDeployTrigger: commit
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: AI_URL
        sync: false
      - key: AI_API_KEY
        sync: false
      - key: AI_COLLECTION
        sync: false
      - key: AI_SHOW_AUTHORS
        value: "false"
      - key: BETTER_AUTH_SECRET
        generateValue: true
      - key: BETTER_AUTH_URL
        sync: false
