import { existsSync, writeFileSync } from 'node:fs'
import { fileURLToPath, pathToFileURL } from 'node:url'
import openapiTS, { astToString } from 'openapi-typescript'

// Default: the draft spec in packages/ai-contract. `--remote`: the live FastAPI spec at ${AI_URL}/openapi.json.
const rootEnvFile = fileURLToPath(new URL('../../../.env', import.meta.url))
if (existsSync(rootEnvFile)) process.loadEnvFile(rootEnvFile)

const draftFile = fileURLToPath(new URL('../../../packages/ai-contract/openapi.yaml', import.meta.url))
const outFile = fileURLToPath(new URL('../src/lib/ai/schema.d.ts', import.meta.url))

function fail(message) {
  console.error(`\n✖ gen:ai failed: ${message}\n`)
  process.exit(1)
}

let source
if (process.argv.includes('--remote')) {
  const baseUrl = process.env.AI_URL
  if (!baseUrl) fail('AI_URL is not set. Add it to the root .env (see .env.example).')
  const schemaUrl = `${baseUrl.replace(/\/+$/, '')}/openapi.json`
  let response
  try {
    response = await fetch(schemaUrl, { signal: AbortSignal.timeout(5000) })
  } catch (err) {
    const reason = err.cause?.code ?? err.name ?? 'network error'
    fail(`could not reach the AI service at ${schemaUrl} (${reason}).\n  Is it running? Is AI_URL in the root .env correct?`)
  }
  if (!response.ok) fail(`${schemaUrl} responded with HTTP ${response.status}.`)
  try {
    source = { label: schemaUrl, spec: await response.json() }
  } catch {
    fail(`${schemaUrl} did not return JSON. Is AI_URL pointing at the FastAPI service?`)
  }
} else {
  source = { label: 'packages/ai-contract/openapi.yaml', spec: pathToFileURL(draftFile) }
}

let output
try {
  output = astToString(await openapiTS(source.spec))
} catch (err) {
  fail(`the schema at ${source.label} is not a valid OpenAPI document: ${err.message}`)
}

writeFileSync(outFile, `// Generated by \`pnpm gen:ai\` from ${source.label}. Do not edit by hand.\n\n${output}`)
console.log(`✔ Wrote ${outFile}`)
