// Generated by `pnpm gen:ai` from packages/ai-contract/openapi.yaml. Do not edit by hand.

export interface paths {
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Match a resident's query against the knowledge base, split by match tier. */
        post: operations["search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The whole knowledge base as tiles for browsing (Baza wiedzy). Small enough to filter and page on the client. */
        get: operations["catalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CatalogResponse: {
            items: components["schemas"]["CatalogItem"][];
        };
        CatalogItem: {
            id: string;
            title: string;
            summary: string;
            /** @example Innowacje dla seniorów */
            category?: string;
            /**
             * @description Stable category key for icons and filters. From record.category_slug.
             * @example dla-seniorow
             */
            categorySlug?: string;
            source: components["schemas"]["Source"];
        };
        SearchRequest: {
            /**
             * @description Chroma collection name to search. Exact name TBD with the AI dev.
             * @example knowledge
             */
            collection: string;
            /**
             * @description The resident's free-form problem description (Zapytanie).
             * @example mama sama nie daje rady z opieką nad tatą po udarze
             */
            query: string;
        };
        SearchResponse: {
            /** @description High-match results (Rozwiązania). */
            solutions: components["schemas"]["Result"][];
            /** @description Medium-match results for the same query (Rozwiązania pokrewne). */
            related: components["schemas"]["Result"][];
            /** @description True when nothing passed the lower threshold (Brak odpowiedzi). */
            noMatch: boolean;
        };
        Result: {
            id: string;
            kind: components["schemas"]["ResultKind"];
            title: string;
            /** @description Short plain-language description. For innovations = record.solution (fallback record.problem); not the scraped description. */
            summary: string;
            /**
             * @description Who the result is for (Kategoria), e.g. "Innowacje dla seniorów". From record.category_name.
             * @example Innowacje dla seniorów
             */
            category?: string;
            /**
             * @description Stable category key for icons and filters. From record.category_slug.
             * @example dla-seniorow
             */
            categorySlug?: string;
            /** @description Match rationale (Uzasadnienie dopasowania), grounded in this result only. */
            why: string;
            /** @description True when `why` was written by an LLM, so the UI labels it as AI content. False for template text. */
            whyGenerated: boolean;
            source: components["schemas"]["Source"];
            details?: components["schemas"]["Details"];
            links?: components["schemas"]["Links"];
        };
        /** @description Longer content shown when the resident expands a result. */
        Details: {
            /** @description From record.problem. */
            problem?: string;
            /** @description From record.target_group. */
            targetGroup?: string;
            /** @description From record.effectiveness. */
            effectiveness?: string;
        };
        /** @description Media for result actions (S-02). Never include record.authors (real personal data). */
        Links: {
            /**
             * Format: uri
             * @description From record.youtube_video.
             */
            video?: string;
            /**
             * Format: uri
             * @description First of record.details_pdf.
             */
            pdf?: string;
            /**
             * Format: uri
             * @description From record.file_zip. Implementation materials, not shown to residents.
             */
            download?: string;
            /** @description Contact phone for helpers, e.g. "+48 12 345 67 89". */
            phone?: string;
        };
        /** @enum {string} */
        ResultKind: "innovation" | "helper" | "fact";
        Source: {
            /** @example Biblioteka Innowacji Społecznych */
            label: string;
            /**
             * Format: uri
             * @description For innovations = record.source_url.
             */
            url?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Results already split by match tier (thresholds are applied by the AI service). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
    catalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All knowledge-base items. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogResponse"];
                };
            };
        };
    };
}
