// Generated by `pnpm gen:ai` from packages/ai-contract/vector-api.json (the AI dev's Chroma API). Do not edit by hand.

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API root info
         * @description Returns basic API metadata, active embedding model, and endpoint map.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service information */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RootInfoResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Checks Chroma DB connectivity, storage status, and Gemini API key readiness.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description System is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
                /** @description Service unhealthy */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all collections
         * @description Returns a list of all collections with metadata and record counts.
         */
        get: {
            parameters: {
                query?: {
                    /** @description API Authorization Key */
                    api_key?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of collections */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CollectionsResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a new collection
         * @description Explicitly creates a collection with optional custom metadata.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCollectionRequest"];
                };
            };
            responses: {
                /** @description Collection created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SingleCollectionResponse"];
                    };
                };
                /** @description Invalid collection name or already exists */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Validation Error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collections/{collection_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get collection details */
        get: {
            parameters: {
                query?: {
                    /** @description API Authorization Key */
                    api_key?: string;
                };
                header?: never;
                path: {
                    /** @description Name of the collection */
                    collection_name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Collection details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SingleCollectionResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Collection not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a collection */
        delete: {
            parameters: {
                query?: {
                    /** @description API Authorization Key */
                    api_key?: string;
                };
                header?: never;
                path: {
                    /** @description Name of the collection to delete */
                    collection_name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Collection deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessMessageResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Error deleting collection */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve documents
         * @description Retrieve documents by comma-separated IDs or list with pagination.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Comma-separated IDs */
                    ids?: string;
                    /** @description Max documents */
                    limit?: number;
                    /** @description Pagination offset */
                    offset?: number;
                    /** @description Target collection */
                    collection_name?: string;
                    /** @description API Key */
                    api_key?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Retrieved documents */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GetDocumentsResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /**
         * Edit / update existing records
         * @description Updates text content, metadata, or both for existing document IDs.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateDocumentsRequest"];
                };
            };
            responses: {
                /** @description Records updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocumentActionResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationError"];
                    };
                };
            };
        };
        /**
         * Ingest new documents
         * @description Embeds and stores documents in the vector database.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddDocumentsRequest"];
                };
            };
            responses: {
                /** @description Documents added successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocumentActionResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Schema validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationError"];
                    };
                };
            };
        };
        /**
         * Delete documents
         * @description Deletes documents from the collection by ID.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DeleteDocumentsRequest"];
                };
            };
            responses: {
                /** @description Documents deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeleteDocumentsResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationError"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/upsert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upsert documents
         * @description Inserts records if missing, or updates them if they already exist.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpsertDocumentsRequest"];
                };
            };
            responses: {
                /** @description Documents upserted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocumentActionResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Semantic vector search
         * @description Executes semantic similarity search against the vector database using Gemini embeddings.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["QueryRequest"];
                };
            };
            responses: {
                /** @description Semantic query results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QueryResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RootInfoResponse: {
            name: string;
            status: string;
            embedding_model: string;
            mock_mode?: boolean;
            docs?: {
                [key: string]: string;
            };
        };
        HealthResponse: {
            /** @example healthy */
            status: string;
            /** @example /app/chroma_data */
            chroma_storage: string;
            /** @example gemini-embedding-2 */
            embedding_model: string;
            /** @example true */
            gemini_api_key_configured?: boolean;
            /** @example true */
            auth_enabled: boolean;
            /** @example false */
            mock_embeddings_enabled?: boolean;
            /** @example 1 */
            collections_count?: number;
        };
        CollectionItem: {
            /** @example rops_innovations */
            name: string;
            /** @example 115 */
            count: number;
            metadata?: {
                [key: string]: unknown;
            };
        };
        CollectionsResponse: {
            /** @example success */
            status: string;
            collections: components["schemas"]["CollectionItem"][];
        };
        SingleCollectionResponse: {
            /** @example success */
            status: string;
            message?: string;
            collection: components["schemas"]["CollectionItem"];
        };
        QueryMatch: {
            /** @example dla-seniorow__bawita */
            id: string;
            document?: string | null;
            metadata?: {
                [key: string]: unknown;
            } | null;
            /**
             * Format: float
             * @example 0.3875
             */
            distance?: number | null;
        };
        QueryResultItem: {
            query: string;
            matches: components["schemas"]["QueryMatch"][];
        };
        QueryResponse: {
            /** @example success */
            status: string;
            /** @example rops_innovations */
            collection: string;
            results: components["schemas"]["QueryResultItem"][];
        };
        DocumentsData: {
            ids: string[];
            documents?: (string | null)[];
            metadatas?: (Record<string, never> | null)[];
        };
        GetDocumentsResponse: {
            /** @example success */
            status: string;
            collection: string;
            total?: number;
            limit?: number;
            offset?: number;
            data: components["schemas"]["DocumentsData"];
        };
        DocumentActionResponse: {
            /** @example success */
            status: string;
            /** @example upserted */
            action?: string;
            /** @example rops_innovations */
            collection: string;
            ids: string[];
        };
        DeleteDocumentsResponse: {
            /** @example success */
            status: string;
            collection: string;
            deleted_ids: string[];
        };
        SuccessMessageResponse: {
            /** @example success */
            status: string;
            message: string;
        };
        ErrorResponse: {
            /** @example error */
            status: string;
            /** @example Operation failed */
            message: string;
        };
        ValidationError: {
            /** @example error */
            status: string;
            /** @example Validation failed */
            message: string;
            errors?: {
                field: string;
                message: string;
                type?: string;
            }[];
        };
        CreateCollectionRequest: {
            /** @description Unique collection name (3-63 chars) */
            name: string;
            /** @description Optional custom metadata dict */
            metadata?: Record<string, never>;
            /** @description API key if not using header auth */
            api_key?: string;
        };
        AddDocumentsRequest: {
            /** @description Document texts */
            documents: string[];
            /** @description Optional IDs (auto-generated if omitted) */
            ids?: string[];
            /** @description Optional metadata objects */
            metadatas?: Record<string, never>[];
            /** @description Target collection name */
            collection_name?: string;
            /** @description API key if not using header auth */
            api_key?: string;
        };
        UpdateDocumentsRequest: {
            /** @description Document IDs to update */
            ids: string[];
            /** @description Updated document texts */
            documents?: string[];
            /** @description Updated metadata dicts */
            metadatas?: Record<string, never>[];
            /** @description Target collection name */
            collection_name?: string;
            /** @default false */
            upsert: boolean;
            /** @description API key if not using header auth */
            api_key?: string;
        };
        UpsertDocumentsRequest: {
            /** @description Document IDs */
            ids: string[];
            /** @description Document texts */
            documents: string[];
            /** @description Metadata dicts */
            metadatas?: Record<string, never>[];
            /** @description Target collection name */
            collection_name?: string;
            /** @description API key if not using header auth */
            api_key?: string;
        };
        DeleteDocumentsRequest: {
            /** @description Document IDs to delete */
            ids: string[];
            /** @description Target collection name */
            collection_name?: string;
            /** @description API key if not using header auth */
            api_key?: string;
        };
        QueryRequest: {
            /** @description Search query string */
            query?: string;
            /** @description Batch queries */
            query_texts?: string[];
            /**
             * @description Number of matches
             * @default 5
             */
            n_results: number;
            /** @description Chroma metadata filter */
            where?: Record<string, never>;
            /** @description Target collection name */
            collection_name?: string;
            /** @description API key if not using header auth */
            api_key?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
