// Generated by `pnpm gen:ai` from packages/ai-contract/vector-api.json (the AI dev's Chroma API). Do not edit by hand.

export interface paths {
    "/api/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Semantic search across ROPS innovations
         * @description Performs vector similarity search using `gemini-embedding-2` in 3072 dimensions.
         *
         *     **Key Features:**
         *     - Target collection defaults to `rops_innovations`.
         *     - Supports natural Polish queries (e.g. *stymulacja pamięci seniora*, *inteligentne czujniki do leków*).
         *     - Supports Chroma metadata filtering via `where` (e.g. `{"category_slug": "dla-seniorow"}`).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["QueryRequest"];
                };
            };
            responses: {
                /** @description Ranked semantic search results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "status": "success",
                         *       "collection": "rops_innovations",
                         *       "results": [
                         *         {
                         *           "query": "inteligentne opaski i czujniki dla seniorów",
                         *           "matches": [
                         *             {
                         *               "id": "dla-seniorow__therapy-set",
                         *               "distance": 0.4188,
                         *               "document": "Tytuł innowacji: Therapy Set\n\nKategoria: Innowacje dla seniorów\n\nProblem: Ograniczona dostępność terapii zajęciowej dla seniorów...",
                         *               "metadata": {
                         *                 "title": "Therapy Set",
                         *                 "category_id": 1,
                         *                 "category_name": "Innowacje dla seniorów",
                         *                 "category_slug": "dla-seniorow",
                         *                 "authors": "Joanna Krokosz",
                         *                 "source_url": "https://rops.krakow.pl/innowacje-spoleczne/biblioteka-innowacji-spolecznych/dla-seniorow,therapy-set",
                         *                 "file_zip": "https://rops.krakow.pl/pliki/IS/bibloteka/therapyset.zip",
                         *                 "youtube_video": "",
                         *                 "details_pdf": "[\"https://rops.krakow.pl/mpliki/IS/BIBLIOTEKA_INNOWACJI_SPOECZNYCH/Zasady_wykorzystania_innowacji_MIIS.pdf\"]",
                         *                 "data_source": "rops.krakow.pl",
                         *                 "scrape_timestamp": "2026-10-03",
                         *                 "index": 16
                         *               }
                         *             },
                         *             {
                         *               "id": "dla-zdrowia-i-medycyny__inteligentny-organizer-do-lekow",
                         *               "distance": 0.4375,
                         *               "document": "Tytuł innowacji: Inteligentny organizer do leków\n\nKategoria: Innowacje dla zdrowia i medycyny\n\nRozwiązanie: Narzędzie wyposażone w czujniki...",
                         *               "metadata": {
                         *                 "title": "Inteligentny organizer do leków",
                         *                 "category_id": 9,
                         *                 "category_name": "Innowacje dla zdrowia i medycyny",
                         *                 "category_slug": "dla-zdrowia-i-medycyny",
                         *                 "authors": "Krzysztof Lingo Wojciech Sójka",
                         *                 "source_url": "https://rops.krakow.pl/innowacje-spoleczne/biblioteka-innowacji-spolecznych/dla-zdrowia-i-medycyny,inteligentny-organizer-do-lekow",
                         *                 "file_zip": "https://rops.krakow.pl/pliki/IS/bibloteka/inteligentnyorganizer.zip",
                         *                 "details_pdf": "[]",
                         *                 "index": 111
                         *               }
                         *             }
                         *           ]
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": components["schemas"]["QueryResponse"];
                    };
                };
                /** @description Unauthorized (invalid or missing api_key) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Validation error in request parameters */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List collections
         * @description Lists all Chroma DB collections with record counts and indexing metrics.
         */
        get: {
            parameters: {
                query?: {
                    /** @description API Authorization Key */
                    api_key?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of collections */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "status": "success",
                         *       "collections": [
                         *         {
                         *           "name": "rops_innovations",
                         *           "count": 115,
                         *           "metadata": {
                         *             "hnsw:space": "cosine"
                         *           }
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": components["schemas"]["CollectionsResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create collection
         * @description Explicitly creates a collection. Requires administrative authorization (ADMIN_API_KEY).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "admin_api_key": "YOUR_ADMIN_API_KEY",
                     *       "name": "rops_innovations",
                     *       "metadata": {
                     *         "hnsw:space": "cosine",
                     *         "topic": "rops_social_innovations"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["CreateCollectionRequest"];
                };
            };
            responses: {
                /** @description Collection created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SingleCollectionResponse"];
                    };
                };
                /** @description Collection already exists */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Forbidden - Standard API key does not have permission to create collections */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collections/{collection_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get collection info
         * @description Retrieves count and metadata for a specific collection.
         */
        get: {
            parameters: {
                query?: {
                    /** @description API Key */
                    api_key?: string;
                };
                header?: never;
                path: {
                    /** @description Name of the collection */
                    collection_name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Collection details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "status": "success",
                         *       "collection": {
                         *         "name": "rops_innovations",
                         *         "count": 115,
                         *         "metadata": {
                         *           "hnsw:space": "cosine"
                         *         }
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["SingleCollectionResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Collection not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete collection
         * @description Deletes a collection and all of its records. Requires administrative authorization (ADMIN_API_KEY).
         */
        delete: {
            parameters: {
                query?: {
                    /** @description API Key */
                    api_key?: string;
                    /** @description Administrative API Key */
                    admin_api_key?: string;
                };
                header?: never;
                path: {
                    /** @description Name of collection to delete */
                    collection_name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Collection deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessMessageResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Forbidden - Standard API key cannot delete collections */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve documents from collection
         * @description Fetches documents from `rops_innovations` by ID or with pagination.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Collection name (defaults to rops_innovations) */
                    collection_name?: string;
                    /** @description Comma-separated IDs */
                    ids?: string;
                    /** @description Max records to return */
                    limit?: number;
                    /** @description Offset for pagination */
                    offset?: number;
                    /** @description API Key */
                    api_key?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Retrieved documents */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "status": "success",
                         *       "collection": "rops_innovations",
                         *       "total": 115,
                         *       "limit": 1,
                         *       "offset": 0,
                         *       "data": {
                         *         "ids": [
                         *           "dla-seniorow__bawita"
                         *         ],
                         *         "documents": [
                         *           "Tytuł innowacji: BaWita\n\nKategoria: Innowacje dla seniorów\n\nRozwiązanie: Narzędzie rehabilitacyjne w postaci drewnianej tablicy..."
                         *         ],
                         *         "metadatas": [
                         *           {
                         *             "title": "BaWita",
                         *             "category_id": 1,
                         *             "category_name": "Innowacje dla seniorów",
                         *             "category_slug": "dla-seniorow",
                         *             "authors": "- Maria Lorenc - Maciej Parol",
                         *             "source_url": "https://rops.krakow.pl/innowacje-spoleczne/biblioteka-innowacji-spolecznych/dla-seniorow,bawita",
                         *             "file_zip": "https://rops.krakow.pl/pliki/IS/bibloteka/bawita.zip",
                         *             "youtube_video": "https://www.youtube.com/watch?v=o7UhDlebLJo"
                         *           }
                         *         ]
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["GetDocumentsResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /** Update existing documents */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateDocumentsRequest"];
                };
            };
            responses: {
                /** @description Documents updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocumentActionResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationError"];
                    };
                };
            };
        };
        /**
         * Add documents to collection
         * @description Generates embeddings and adds new documents into `rops_innovations`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "api_key": "YOUR_API_KEY",
                     *       "collection_name": "rops_innovations",
                     *       "ids": [
                     *         "nowa_innowacja_1"
                     *       ],
                     *       "documents": [
                     *         "Tytuł innowacji: Nowa Innowacja Senioralna\n\nKategoria: Innowacje dla seniorów..."
                     *       ],
                     *       "metadatas": [
                     *         {
                     *           "title": "Nowa Innowacja Senioralna",
                     *           "category_slug": "dla-seniorow"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["AddDocumentsRequest"];
                };
            };
            responses: {
                /** @description Documents added */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocumentActionResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationError"];
                    };
                };
            };
        };
        /** Delete documents by ID */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "api_key": "YOUR_API_KEY",
                     *       "collection_name": "rops_innovations",
                     *       "ids": [
                     *         "dla-seniorow__bawita"
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["DeleteDocumentsRequest"];
                };
            };
            responses: {
                /** @description Documents deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeleteDocumentsResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/upsert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upsert documents (insert or update)
         * @description Upserts documents into `rops_innovations`. Automatically generates 3072-dim embeddings using `gemini-embedding-2`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "api_key": "YOUR_API_KEY",
                     *       "collection_name": "rops_innovations",
                     *       "ids": [
                     *         "dla-seniorow__bawita"
                     *       ],
                     *       "documents": [
                     *         "Tytuł innowacji: BaWita\n\nKategoria: Innowacje dla seniorów\n\nProblem: Zespoły otępienne..."
                     *       ],
                     *       "metadatas": [
                     *         {
                     *           "title": "BaWita",
                     *           "category_slug": "dla-seniorow",
                     *           "authors": "Maria Lorenc"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["UpsertDocumentsRequest"];
                };
            };
            responses: {
                /** @description Documents upserted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocumentActionResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check & readiness */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "status": "healthy",
                         *       "chroma_storage": "/app/chroma_data",
                         *       "embedding_model": "gemini-embedding-2",
                         *       "gemini_api_key_configured": true,
                         *       "auth_enabled": true,
                         *       "mock_embeddings_enabled": false,
                         *       "collections_count": 1
                         *     }
                         */
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root service metadata */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service root info */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "name": "HackYeah 2026 - Flask ChromaDB API",
                         *       "status": "online",
                         *       "embedding_model": "gemini-embedding-2",
                         *       "mock_mode": false,
                         *       "docs": {
                         *         "health": "GET /health",
                         *         "swagger_ui": "GET /docs",
                         *         "openapi_spec": "GET /openapi.json",
                         *         "list_collections": "GET /api/collections",
                         *         "query": "POST /api/query"
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["RootInfoResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Metadata attributes for a ROPS Social Innovation */
        ROPSMetadata: {
            /**
             * @description Innovation title
             * @example BaWita
             */
            title?: string;
            /**
             * @description Category numeric ID (1-9)
             * @example 1
             */
            category_id?: number;
            /**
             * @description Human-readable category name
             * @example Innowacje dla seniorów
             */
            category_name?: string;
            /**
             * @description URL slug for category
             * @example dla-seniorow
             */
            category_slug?: string;
            /**
             * @description Authors / innovators
             * @example - Maria Lorenc - Maciej Parol
             */
            authors?: string;
            /**
             * @description Official portal source URL
             * @example https://rops.krakow.pl/innowacje-spoleczne/biblioteka-innowacji-spolecznych/dla-seniorow,bawita
             */
            source_url?: string;
            /**
             * @description Downloadable ZIP package with blueprints/manuals
             * @example https://rops.krakow.pl/pliki/IS/bibloteka/bawita.zip
             */
            file_zip?: string;
            /**
             * @description YouTube demonstration video URL
             * @example https://www.youtube.com/watch?v=o7UhDlebLJo
             */
            youtube_video?: string;
            /**
             * @description JSON array of attached PDF document URLs
             * @example ["https://rops.krakow.pl/mpliki/IS/...pdf"]
             */
            details_pdf?: string;
            /** @example rops.krakow.pl */
            data_source?: string;
            /** @example 2026-10-03 */
            scrape_timestamp?: string;
            /**
             * @description Catalog index 1..115
             * @example 1
             */
            index?: number;
        };
        QueryMatch: {
            /**
             * @description Unique document ID
             * @example dla-seniorow__bawita
             */
            id: string;
            /** @description Clean document text */
            document?: string | null;
            metadata?: components["schemas"]["ROPSMetadata"];
            /**
             * Format: float
             * @description Cosine distance (lower = higher similarity)
             * @example 0.3875
             */
            distance?: number | null;
        };
        QueryResultItem: {
            /** @example inteligentne opaski i czujniki dla seniorów */
            query: string;
            matches: components["schemas"]["QueryMatch"][];
        };
        QueryResponse: {
            /** @example success */
            status: string;
            /** @example rops_innovations */
            collection: string;
            results: components["schemas"]["QueryResultItem"][];
        };
        QueryRequest: {
            /**
             * @description Search query text in natural language
             * @example inteligentne opaski i czujniki dla seniorów
             */
            query?: string;
            /** @description Optional batch of search queries */
            query_texts?: string[];
            /**
             * @description Target collection (defaults to rops_innovations)
             * @default rops_innovations
             * @example rops_innovations
             */
            collection_name: string;
            /**
             * @description Number of top matching documents to return
             * @default 5
             * @example 3
             */
            n_results: number;
            /**
             * @description Chroma DB metadata filtering expression
             * @example {
             *       "category_slug": "dla-seniorow"
             *     }
             */
            where?: Record<string, never>;
            /**
             * @description API Authorization Key
             * @example YOUR_API_KEY
             */
            api_key?: string;
            /**
             * Format: float
             * @description Maximum cosine distance threshold. Excludes matches with distance > max_distance (lower distance = closer match).
             * @example 0.45
             */
            max_distance?: number;
            /**
             * Format: float
             * @description Alias for max_distance.
             */
            distance_threshold?: number;
        };
        CollectionItem: {
            /** @example rops_innovations */
            name: string;
            /** @example 115 */
            count: number;
            /**
             * @example {
             *       "hnsw:space": "cosine"
             *     }
             */
            metadata?: {
                [key: string]: unknown;
            };
        };
        CollectionsResponse: {
            /** @example success */
            status: string;
            collections: components["schemas"]["CollectionItem"][];
        };
        SingleCollectionResponse: {
            /** @example success */
            status: string;
            message?: string;
            collection: components["schemas"]["CollectionItem"];
        };
        GetDocumentsResponse: {
            /** @example success */
            status: string;
            /** @example rops_innovations */
            collection: string;
            /** @example 115 */
            total?: number;
            /** @example 10 */
            limit?: number;
            /** @example 0 */
            offset?: number;
            data: {
                ids: string[];
                documents?: (string | null)[];
                metadatas?: components["schemas"]["ROPSMetadata"][];
            };
        };
        DocumentActionResponse: {
            /** @example success */
            status: string;
            /** @example upserted */
            action?: string;
            /** @example rops_innovations */
            collection: string;
            ids: string[];
        };
        DeleteDocumentsResponse: {
            /** @example success */
            status: string;
            /** @example rops_innovations */
            collection: string;
            deleted_ids: string[];
        };
        HealthResponse: {
            /** @example healthy */
            status: string;
            /** @example /app/chroma_data */
            chroma_storage: string;
            /** @example gemini-embedding-2 */
            embedding_model: string;
            /** @example true */
            gemini_api_key_configured?: boolean;
            /** @example true */
            auth_enabled: boolean;
            /** @example false */
            mock_embeddings_enabled?: boolean;
            /** @example 1 */
            collections_count?: number;
            /**
             * @description Whether administrative key authentication is configured
             * @example true
             */
            admin_auth_enabled?: boolean;
        };
        RootInfoResponse: {
            name: string;
            status: string;
            embedding_model: string;
            mock_mode?: boolean;
            docs?: {
                [key: string]: string;
            };
        };
        SuccessMessageResponse: {
            /** @example success */
            status: string;
            message: string;
        };
        ErrorResponse: {
            /** @example error */
            status: string;
            /** @example Unauthorized or resource not found */
            message: string;
        };
        ValidationError: {
            /** @example error */
            status: string;
            /** @example Validation failed */
            message: string;
            errors?: {
                field: string;
                message: string;
                type?: string;
            }[];
        };
        CreateCollectionRequest: {
            /** @example rops_innovations */
            name: string;
            /**
             * @example {
             *       "topic": "rops_social_innovations"
             *     }
             */
            metadata?: Record<string, never>;
            api_key?: string;
            /** @description Admin authorization key required to create collections */
            admin_api_key?: string;
        };
        AddDocumentsRequest: {
            documents: string[];
            ids?: string[];
            metadatas?: Record<string, never>[];
            /** @default rops_innovations */
            collection_name: string;
            api_key?: string;
        };
        UpdateDocumentsRequest: {
            ids: string[];
            documents?: string[];
            metadatas?: Record<string, never>[];
            /** @default rops_innovations */
            collection_name: string;
            /** @default false */
            upsert: boolean;
            api_key?: string;
        };
        UpsertDocumentsRequest: {
            ids: string[];
            documents: string[];
            metadatas?: Record<string, never>[];
            /** @default rops_innovations */
            collection_name: string;
            api_key?: string;
        };
        DeleteDocumentsRequest: {
            ids: string[];
            /** @default rops_innovations */
            collection_name: string;
            api_key?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
