/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PanelAuthedRouteImport } from './routes/panel/_authed'
import { Route as PanelLoginRouteImport } from './routes/panel/login'
import { Route as PanelAuthedIndexRouteImport } from './routes/panel/_authed/index'
import { Route as PanelAuthedZgloszeniaRouteImport } from './routes/panel/_authed/zgloszenia'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelAuthedRoute = PanelAuthedRouteImport.update({
  id: '/panel/_authed',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelLoginRoute = PanelLoginRouteImport.update({
  id: '/panel/login',
  path: '/panel/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelAuthedIndexRoute = PanelAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelAuthedRoute,
} as any)
const PanelAuthedZgloszeniaRoute = PanelAuthedZgloszeniaRouteImport.update({
  id: '/zgloszenia',
  path: '/zgloszenia',
  getParentRoute: () => PanelAuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/panel': typeof PanelAuthedRouteWithChildren
  '/panel/login': typeof PanelLoginRoute
  '/panel/zgloszenia': typeof PanelAuthedZgloszeniaRoute
  '/panel/': typeof PanelAuthedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/panel/login': typeof PanelLoginRoute
  '/panel/zgloszenia': typeof PanelAuthedZgloszeniaRoute
  '/panel': typeof PanelAuthedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/panel/_authed': typeof PanelAuthedRouteWithChildren
  '/panel/login': typeof PanelLoginRoute
  '/panel/_authed/zgloszenia': typeof PanelAuthedZgloszeniaRoute
  '/panel/_authed/': typeof PanelAuthedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/panel' | '/panel/login' | '/panel/zgloszenia' | '/panel/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/panel/login' | '/panel/zgloszenia' | '/panel'
  id:
    | '__root__'
    | '/'
    | '/panel/_authed'
    | '/panel/login'
    | '/panel/_authed/zgloszenia'
    | '/panel/_authed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PanelAuthedRoute: typeof PanelAuthedRouteWithChildren
  PanelLoginRoute: typeof PanelLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/_authed': {
      id: '/panel/_authed'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelAuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/login': {
      id: '/panel/login'
      path: '/panel/login'
      fullPath: '/panel/login'
      preLoaderRoute: typeof PanelLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/_authed/': {
      id: '/panel/_authed/'
      path: '/'
      fullPath: '/panel/'
      preLoaderRoute: typeof PanelAuthedIndexRouteImport
      parentRoute: typeof PanelAuthedRoute
    }
    '/panel/_authed/zgloszenia': {
      id: '/panel/_authed/zgloszenia'
      path: '/zgloszenia'
      fullPath: '/panel/zgloszenia'
      preLoaderRoute: typeof PanelAuthedZgloszeniaRouteImport
      parentRoute: typeof PanelAuthedRoute
    }
  }
}

interface PanelAuthedRouteChildren {
  PanelAuthedZgloszeniaRoute: typeof PanelAuthedZgloszeniaRoute
  PanelAuthedIndexRoute: typeof PanelAuthedIndexRoute
}

const PanelAuthedRouteChildren: PanelAuthedRouteChildren = {
  PanelAuthedZgloszeniaRoute: PanelAuthedZgloszeniaRoute,
  PanelAuthedIndexRoute: PanelAuthedIndexRoute,
}

const PanelAuthedRouteWithChildren = PanelAuthedRoute._addFileChildren(
  PanelAuthedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PanelAuthedRoute: PanelAuthedRouteWithChildren,
  PanelLoginRoute: PanelLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
