/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as PomyslRouteImport } from './routes/pomysl'
import { Route as InnowacjaIdRouteImport } from './routes/innowacja.$id'
import { Route as PanelAuthedRouteImport } from './routes/panel/_authed'
import { Route as PanelLoginRouteImport } from './routes/panel/login'
import { Route as PanelAuthedIndexRouteImport } from './routes/panel/_authed/index'
import { Route as PanelAuthedNeedsRouteImport } from './routes/panel/_authed/needs'
import { Route as PanelAuthedIdeasIndexRouteImport } from './routes/panel/_authed/ideas/index'
import { Route as PanelAuthedIdeasIdeaIdRouteImport } from './routes/panel/_authed/ideas/$ideaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const PomyslRoute = PomyslRouteImport.update({
  id: '/pomysl',
  path: '/pomysl',
  getParentRoute: () => rootRouteImport,
} as any)
const InnowacjaIdRoute = InnowacjaIdRouteImport.update({
  id: '/innowacja/$id',
  path: '/innowacja/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelAuthedRoute = PanelAuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => PanelRoute,
} as any)
const PanelLoginRoute = PanelLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PanelRoute,
} as any)
const PanelAuthedIndexRoute = PanelAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelAuthedRoute,
} as any)
const PanelAuthedNeedsRoute = PanelAuthedNeedsRouteImport.update({
  id: '/needs',
  path: '/needs',
  getParentRoute: () => PanelAuthedRoute,
} as any)
const PanelAuthedIdeasIndexRoute = PanelAuthedIdeasIndexRouteImport.update({
  id: '/ideas/',
  path: '/ideas/',
  getParentRoute: () => PanelAuthedRoute,
} as any)
const PanelAuthedIdeasIdeaIdRoute = PanelAuthedIdeasIdeaIdRouteImport.update({
  id: '/ideas/$ideaId',
  path: '/ideas/$ideaId',
  getParentRoute: () => PanelAuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/panel': typeof PanelRouteWithChildren
  '/pomysl': typeof PomyslRoute
  '/innowacja/$id': typeof InnowacjaIdRoute
  '/panel/login': typeof PanelLoginRoute
  '/panel/needs': typeof PanelAuthedNeedsRoute
  '/panel/': typeof PanelAuthedIndexRoute
  '/panel/ideas/$ideaId': typeof PanelAuthedIdeasIdeaIdRoute
  '/panel/ideas/': typeof PanelAuthedIdeasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/panel': typeof PanelAuthedIndexRoute
  '/pomysl': typeof PomyslRoute
  '/innowacja/$id': typeof InnowacjaIdRoute
  '/panel/login': typeof PanelLoginRoute
  '/panel/needs': typeof PanelAuthedNeedsRoute
  '/panel/ideas/$ideaId': typeof PanelAuthedIdeasIdeaIdRoute
  '/panel/ideas': typeof PanelAuthedIdeasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/panel': typeof PanelRouteWithChildren
  '/pomysl': typeof PomyslRoute
  '/innowacja/$id': typeof InnowacjaIdRoute
  '/panel/_authed': typeof PanelAuthedRouteWithChildren
  '/panel/login': typeof PanelLoginRoute
  '/panel/_authed/needs': typeof PanelAuthedNeedsRoute
  '/panel/_authed/': typeof PanelAuthedIndexRoute
  '/panel/_authed/ideas/$ideaId': typeof PanelAuthedIdeasIdeaIdRoute
  '/panel/_authed/ideas/': typeof PanelAuthedIdeasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/panel'
    | '/pomysl'
    | '/innowacja/$id'
    | '/panel/login'
    | '/panel/needs'
    | '/panel/'
    | '/panel/ideas/$ideaId'
    | '/panel/ideas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/panel'
    | '/pomysl'
    | '/innowacja/$id'
    | '/panel/login'
    | '/panel/needs'
    | '/panel/ideas/$ideaId'
    | '/panel/ideas'
  id:
    | '__root__'
    | '/'
    | '/panel'
    | '/pomysl'
    | '/innowacja/$id'
    | '/panel/_authed'
    | '/panel/login'
    | '/panel/_authed/needs'
    | '/panel/_authed/'
    | '/panel/_authed/ideas/$ideaId'
    | '/panel/_authed/ideas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PanelRoute: typeof PanelRouteWithChildren
  PomyslRoute: typeof PomyslRoute
  InnowacjaIdRoute: typeof InnowacjaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pomysl': {
      id: '/pomysl'
      path: '/pomysl'
      fullPath: '/pomysl'
      preLoaderRoute: typeof PomyslRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innowacja/$id': {
      id: '/innowacja/$id'
      path: '/innowacja/$id'
      fullPath: '/innowacja/$id'
      preLoaderRoute: typeof InnowacjaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/_authed': {
      id: '/panel/_authed'
      path: ''
      fullPath: '/panel'
      preLoaderRoute: typeof PanelAuthedRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/login': {
      id: '/panel/login'
      path: '/login'
      fullPath: '/panel/login'
      preLoaderRoute: typeof PanelLoginRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/_authed/': {
      id: '/panel/_authed/'
      path: '/'
      fullPath: '/panel/'
      preLoaderRoute: typeof PanelAuthedIndexRouteImport
      parentRoute: typeof PanelAuthedRoute
    }
    '/panel/_authed/needs': {
      id: '/panel/_authed/needs'
      path: '/needs'
      fullPath: '/panel/needs'
      preLoaderRoute: typeof PanelAuthedNeedsRouteImport
      parentRoute: typeof PanelAuthedRoute
    }
    '/panel/_authed/ideas/': {
      id: '/panel/_authed/ideas/'
      path: '/ideas'
      fullPath: '/panel/ideas/'
      preLoaderRoute: typeof PanelAuthedIdeasIndexRouteImport
      parentRoute: typeof PanelAuthedRoute
    }
    '/panel/_authed/ideas/$ideaId': {
      id: '/panel/_authed/ideas/$ideaId'
      path: '/ideas/$ideaId'
      fullPath: '/panel/ideas/$ideaId'
      preLoaderRoute: typeof PanelAuthedIdeasIdeaIdRouteImport
      parentRoute: typeof PanelAuthedRoute
    }
  }
}

interface PanelAuthedRouteChildren {
  PanelAuthedNeedsRoute: typeof PanelAuthedNeedsRoute
  PanelAuthedIndexRoute: typeof PanelAuthedIndexRoute
  PanelAuthedIdeasIdeaIdRoute: typeof PanelAuthedIdeasIdeaIdRoute
  PanelAuthedIdeasIndexRoute: typeof PanelAuthedIdeasIndexRoute
}

const PanelAuthedRouteChildren: PanelAuthedRouteChildren = {
  PanelAuthedNeedsRoute: PanelAuthedNeedsRoute,
  PanelAuthedIndexRoute: PanelAuthedIndexRoute,
  PanelAuthedIdeasIdeaIdRoute: PanelAuthedIdeasIdeaIdRoute,
  PanelAuthedIdeasIndexRoute: PanelAuthedIdeasIndexRoute,
}

const PanelAuthedRouteWithChildren = PanelAuthedRoute._addFileChildren(
  PanelAuthedRouteChildren,
)

interface PanelRouteChildren {
  PanelAuthedRoute: typeof PanelAuthedRouteWithChildren
  PanelLoginRoute: typeof PanelLoginRoute
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelAuthedRoute: PanelAuthedRouteWithChildren,
  PanelLoginRoute: PanelLoginRoute,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PanelRoute: PanelRouteWithChildren,
  PomyslRoute: PomyslRoute,
  InnowacjaIdRoute: InnowacjaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
