// Generated by `pnpm gen:ai` from packages/ai-contract/openapi.yaml. Do not edit by hand.

export interface paths {
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Match a resident's query against the knowledge base, split by match tier. */
        post: operations["search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SearchRequest: {
            /**
             * @description Knowledge collection to search. Meaning TBD with the AI dev.
             * @example knowledge
             */
            collection: string;
            /**
             * @description The resident's free-form problem description (Zapytanie).
             * @example mama sama nie daje rady z opieką nad tatą po udarze
             */
            query: string;
        };
        SearchResponse: {
            /** @description High-match results (Rozwiązania). */
            solutions: components["schemas"]["Result"][];
            /** @description Medium-match results for the same query (Rozwiązania pokrewne). */
            related: components["schemas"]["Result"][];
            /** @description True when nothing passed the lower threshold (Brak odpowiedzi). */
            noMatch: boolean;
        };
        Result: {
            id: string;
            kind: components["schemas"]["ResultKind"];
            title: string;
            summary: string;
            /** @description AI-generated match rationale (Uzasadnienie dopasowania), grounded in this result only. */
            why: string;
            source: components["schemas"]["Source"];
        };
        /** @enum {string} */
        ResultKind: "innovation" | "helper" | "fact";
        Source: {
            /** @example Biblioteka Innowacji Społecznych */
            label: string;
            /** Format: uri */
            url?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Results already split by match tier (thresholds are applied by the AI service). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
}
