import { existsSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import openapiTS, { astToString } from 'openapi-typescript'

const rootEnvFile = fileURLToPath(new URL('../../../.env', import.meta.url))
if (existsSync(rootEnvFile)) process.loadEnvFile(rootEnvFile)

const outFile = fileURLToPath(new URL('../src/decide/schema.d.ts', import.meta.url))

function fail(message) {
  console.error(`\n✖ gen:decide failed: ${message}\n`)
  process.exit(1)
}

const baseUrl = process.env.DECIDE_URL
if (!baseUrl) fail('DECIDE_URL is not set. Add it to the root .env (see .env.example).')
const schemaUrl = `${baseUrl.replace(/\/+$/, '')}/openapi.json`

let response
try {
  response = await fetch(schemaUrl, { signal: AbortSignal.timeout(5000) })
} catch (err) {
  const reason = err.cause?.code ?? err.name ?? 'network error'
  fail(`could not reach the AI service at ${schemaUrl} (${reason}).\n  Is it running? Is DECIDE_URL in the root .env correct?`)
}
if (!response.ok) fail(`${schemaUrl} responded with HTTP ${response.status}.`)

let spec
try {
  spec = await response.json()
} catch {
  fail(`${schemaUrl} did not return JSON. Is DECIDE_URL pointing at the FastAPI service?`)
}

let output
try {
  output = astToString(await openapiTS(spec))
} catch (err) {
  fail(`the schema at ${schemaUrl} is not a valid OpenAPI document: ${err.message}`)
}

writeFileSync(outFile, `// Generated by \`pnpm gen:decide\` from ${schemaUrl}. Do not edit by hand.\n\n${output}`)
console.log(`✔ Wrote ${outFile}`)
